### ISSUE TITLE
 Error adding vectors: ... is not a valid class name 

### ISSUE THREAD

**Issue by julianurregoar** [langchain-ai/chat-langchainjs#11]
Hey Brace!

I am facing following issue once the data is being ingested. Maybe, I forgot to add something.

```
Failed to ingest docs
Error: Error adding vectors: Error: 'xxxxxx' is not a valid class name, class 'xxxxx' not present in schema
```

Thanks for sharing this good example!

**Comment by bracesproul** [comment]
Did you add all the required environment variables listed [here](https://github.com/langchain-ai/chat-langchainjs/blob/main/backend/.env.example) and is the code modified at all?

**Comment by Gitmaxd** [comment]
The issue here is likely that you've not provided a schema for the Weaviate vector db.  

No schema, no class.

You'll need to build the Weaviate schema according to their documentation.

https://weaviate.io/developers/academy/zero_to_mvp/schema_and_imports/schema

**Comment by bracesproul** [comment]
Hey @julianurregoar are you still having this issue?

**Comment by julianurregoar** [comment]
Hey Brace, I've not gotten the time to go through it. I will run the app again on Friday then I let you the result.

Hope it would be fixed.

**Comment by julianurregoar** [comment]
Fixed! Thanks!
