### ISSUE TITLE
Chat not working

### ISSUE THREAD

**Issue by shanumas** [langchain-ai/chat-langchainjs#29]
Every time I start with a langchain-repo I spend at least 2 days to get it to work.

If it is not built for windows, just mention it explicitly.  I do not want to waste time.

Just checkedout and have this problem after starting chat:

`✓ Compiled /_error in 960ms (3168 modules)
 ⨯ Error: Error in similaritySearch Error: Cannot query field "russel" on type "GetObjectsObj". Did you mean "Russel"?: {"response":{"errors":[{"locations":[{"column":6,"line":1}],"message":"Cannot query field \"russel\" on type \"GetObjectsObj\". Did you mean \"Russel\"?","path":null}],"status":200,"headers":{}},"request":{"query":"{Get{russel(nearVector:{vector:[-0.0134877665,-0.011036796,-0.009321116,`

What is the issue

![image](https://github.com/langchain-ai/chat-langchainjs/assets/34864140/69f4975f-5274-47b2-a3cf-12d8cf912bae)

**Comment by shamuiscoding** [comment]
It's probably because it is saved as Russel on Weaviate. Weaviate seems to upper case the index name automatically
